/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppok.jooq;


import jp.co.toshiba.ppok.jooq.tables.City;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COUNTRYCODE = Internal.createIndex(DSL.name("CountryCode"), City.CITY, new OrderField[] { City.CITY.COUNTRY_CODE }, false);
}
