/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppok.jooq;


import java.util.Arrays;
import java.util.List;

import jp.co.toshiba.ppok.jooq.tables.City;
import jp.co.toshiba.ppok.jooq.tables.CityInfo;
import jp.co.toshiba.ppok.jooq.tables.Country;
import jp.co.toshiba.ppok.jooq.tables.Language;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.city</code>.
     */
    public final City CITY = City.CITY;

    /**
     * The table <code>public.city_info</code>.
     */
    public final CityInfo CITY_INFO = CityInfo.CITY_INFO;

    /**
     * The table <code>public.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.language</code>.
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            City.CITY,
            CityInfo.CITY_INFO,
            Country.COUNTRY,
            Language.LANGUAGE
        );
    }
}
