/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppok.jooq;


import jp.co.toshiba.ppok.jooq.tables.City;
import jp.co.toshiba.ppok.jooq.tables.CityInfo;
import jp.co.toshiba.ppok.jooq.tables.Country;
import jp.co.toshiba.ppok.jooq.tables.Language;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>public.city_info</code>.
     */
    public static final CityInfo CITY_INFO = CityInfo.CITY_INFO;

    /**
     * The table <code>public.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.language</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;
}
