/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppok.jooq.tables.records;


import jp.co.toshiba.ppok.jooq.tables.City;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityRecord extends UpdatableRecordImpl<CityRecord> implements Record6<Integer, String, String, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.city.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.city.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.city.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.city.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.city.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.city.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.city.district</code>.
     */
    public void setDistrict(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.city.district</code>.
     */
    public String getDistrict() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.city.population</code>.
     */
    public void setPopulation(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.city.population</code>.
     */
    public Integer getPopulation() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.city.delete_flg</code>.
     */
    public void setDeleteFlg(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.city.delete_flg</code>.
     */
    public String getDeleteFlg() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return City.CITY.ID;
    }

    @Override
    public Field<String> field2() {
        return City.CITY.NAME;
    }

    @Override
    public Field<String> field3() {
        return City.CITY.COUNTRY_CODE;
    }

    @Override
    public Field<String> field4() {
        return City.CITY.DISTRICT;
    }

    @Override
    public Field<Integer> field5() {
        return City.CITY.POPULATION;
    }

    @Override
    public Field<String> field6() {
        return City.CITY.DELETE_FLG;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCountryCode();
    }

    @Override
    public String component4() {
        return getDistrict();
    }

    @Override
    public Integer component5() {
        return getPopulation();
    }

    @Override
    public String component6() {
        return getDeleteFlg();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCountryCode();
    }

    @Override
    public String value4() {
        return getDistrict();
    }

    @Override
    public Integer value5() {
        return getPopulation();
    }

    @Override
    public String value6() {
        return getDeleteFlg();
    }

    @Override
    public CityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CityRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CityRecord value3(String value) {
        setCountryCode(value);
        return this;
    }

    @Override
    public CityRecord value4(String value) {
        setDistrict(value);
        return this;
    }

    @Override
    public CityRecord value5(Integer value) {
        setPopulation(value);
        return this;
    }

    @Override
    public CityRecord value6(String value) {
        setDeleteFlg(value);
        return this;
    }

    @Override
    public CityRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CityRecord
     */
    public CityRecord() {
        super(City.CITY);
    }

    /**
     * Create a detached, initialised CityRecord
     */
    public CityRecord(Integer id, String name, String countryCode, String district, Integer population, String deleteFlg) {
        super(City.CITY);

        setId(id);
        setName(name);
        setCountryCode(countryCode);
        setDistrict(district);
        setPopulation(population);
        setDeleteFlg(deleteFlg);
        resetChangedOnNotNull();
    }
}
