/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppok.jooq.tables.records;


import java.math.BigDecimal;

import jp.co.toshiba.ppok.jooq.tables.Language;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageRecord extends UpdatableRecordImpl<LanguageRecord> implements Record5<String, String, String, BigDecimal, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.language.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.language.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.language.language</code>.
     */
    public void setLanguage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.language.language</code>.
     */
    public String getLanguage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.language.is_official</code>.
     */
    public void setIsOfficial(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.language.is_official</code>.
     */
    public String getIsOfficial() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.language.percentage</code>.
     */
    public void setPercentage(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.language.percentage</code>.
     */
    public BigDecimal getPercentage() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.language.delete_flg</code>.
     */
    public void setDeleteFlg(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.language.delete_flg</code>.
     */
    public String getDeleteFlg() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, BigDecimal, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, BigDecimal, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Language.LANGUAGE.COUNTRY_CODE;
    }

    @Override
    public Field<String> field2() {
        return Language.LANGUAGE.LANGUAGE_;
    }

    @Override
    public Field<String> field3() {
        return Language.LANGUAGE.IS_OFFICIAL;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Language.LANGUAGE.PERCENTAGE;
    }

    @Override
    public Field<String> field5() {
        return Language.LANGUAGE.DELETE_FLG;
    }

    @Override
    public String component1() {
        return getCountryCode();
    }

    @Override
    public String component2() {
        return getLanguage();
    }

    @Override
    public String component3() {
        return getIsOfficial();
    }

    @Override
    public BigDecimal component4() {
        return getPercentage();
    }

    @Override
    public String component5() {
        return getDeleteFlg();
    }

    @Override
    public String value1() {
        return getCountryCode();
    }

    @Override
    public String value2() {
        return getLanguage();
    }

    @Override
    public String value3() {
        return getIsOfficial();
    }

    @Override
    public BigDecimal value4() {
        return getPercentage();
    }

    @Override
    public String value5() {
        return getDeleteFlg();
    }

    @Override
    public LanguageRecord value1(String value) {
        setCountryCode(value);
        return this;
    }

    @Override
    public LanguageRecord value2(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public LanguageRecord value3(String value) {
        setIsOfficial(value);
        return this;
    }

    @Override
    public LanguageRecord value4(BigDecimal value) {
        setPercentage(value);
        return this;
    }

    @Override
    public LanguageRecord value5(String value) {
        setDeleteFlg(value);
        return this;
    }

    @Override
    public LanguageRecord values(String value1, String value2, String value3, BigDecimal value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LanguageRecord
     */
    public LanguageRecord() {
        super(Language.LANGUAGE);
    }

    /**
     * Create a detached, initialised LanguageRecord
     */
    public LanguageRecord(String countryCode, String language, String isOfficial, BigDecimal percentage, String deleteFlg) {
        super(Language.LANGUAGE);

        setCountryCode(countryCode);
        setLanguage(language);
        setIsOfficial(isOfficial);
        setPercentage(percentage);
        setDeleteFlg(deleteFlg);
        resetChangedOnNotNull();
    }
}
